### ISSUE TITLE
Error in LossM2_sepLV

### ISSUE THREAD

**Issue by francischuah** [ECONshare/CVPAT#3] opened 2021-06-17 06:44 UTC
Hi, i try to run a simple model consist of formative and reflective indicator and i got the following error.

_Error in LossM2_sepLV[[j]][testIndexes] <- PseudoPredErrorsM2[, (rownames(ReflecSpecM2)[ReflecSpecM2[,  : replacement has length zero_

Can I have an advise what I should do with this error?

**Comment by ECONshare** [comment] 2021-06-17 07:13
Could you post your model specifications, then I can see if I can reproduce the error and then give some advice.

**Comment by francischuah** [comment] 2021-06-17 08:04
Hi,

_link removed_

I have a model with 2 IV, 1 mediator and 1 DV

**Comment by francischuah** [comment] 2021-06-17 10:11
I think I can put up my model specification for you to see here.

Thanks

![Estimated Model](https://user-images.githubusercontent.com/86041835/122377130-62d3ef80-cf97-11eb-8939-8071d685f10c.JPG)
![Alternate model](https://user-images.githubusercontent.com/86041835/122377137-64051c80-cf97-11eb-992f-252e1ca99186.JPG)

**Comment by ECONshare** [comment] 2021-06-17 10:45
Ok, thanks. I think the problem is the formative ENGA. I might have a solution for you. I will get back to you.

**Comment by ECONshare** [comment] 2021-06-17 21:41
The problem is that you have ENGA as endogenous in the EM. The CVPAT function available here cannot compare models with formative endogenous LV. The reason is that it does make theoretical sense to predict a formative indicator from its construct (in the formative measurement model the directionality is from the indicator to the construct). We have been working on a CVPAT package where you can choose to compare the out-of-sample predictive ability on predefined sets of constructs. In your case you could compare the predictive ability only on the "EXE" construct (it is endogenous in both models and reflective). 
To do so, you can download the following file tar.gz file containing the CVPAT package, and install it from R:
[CVPAT_0.1.0.tar.gz](https://github.com/ECONshare/CVPAT/files/6673238/CVPAT_0.1.0.tar.gz)
Notice that this package is still work in progress. However, you can easily use it for your model comparison.

After installing the package you run the code below (notice the lavaan/cSEM model specifications):

```
library(CVPAT)
library(cSEM)
load(file = "LVSEM.rda")

EM <- "
ENGA ~ COMMT + SUPPO
EXE ~ ENGA
ENGA <~ COE + EME + PHE
COMMT  =~ COMT
SUPPO  =~ SUPP
EXE  =~ EXEC
"

AM <- "
SUPPO ~ COMMT + ENGA
EXE ~ SUPPO
ENGA <~ COE + EME + PHE
COMMT  =~ COMT
SUPPO  =~ SUPP
EXE  =~ EXEC
"
res_CVPAT <- cvpat(mv = lvsem, cv_folds = 10,
                   model1 = AM, model2 = EM,
                   hypothesis = "M1_better_out_of_sample_than_M2",
                   compare_on_constructs = NULL,
                   boot_samples= 5000,
                   boot_di = T,
                   rescale_pred_errors = FALSE,
                   seed=42)
res_CVPAT$res
```

The `res_CVPAT$res` gives you the results. Here you should look at the "EXE" column (you should only compare on the endogenous LV that is reflectively measured). You will find that the null hypothesis is rejected in favor of the alternative hypothesis that AM has a lower loss than EM (i.e. that AM has a better predictive ability).  Hope this helps.

**Comment by francischuah** [comment] 2021-06-18 03:19
Hello, thank you for the kind reply. Yes I would like to predict the ultimate outcome EXE only. Thank you for the new package. I will update here in case I encounter any other issue.

**Comment by francischuah** [comment] 2021-06-18 16:40
I have tested the package and the file. It works well. Hopefully the package is available on CRAN soon. Thanks

**Comment by ECONshare** [comment] 2021-06-18 19:19
Glad to hear! I am closing this issue now.

**Closed as completed by ECONshare** 2021-06-18 19:19 UTC
